# Database Paths
app.db.auth-path=./data/authdb
app.db.finance-path=./data/financedb

# Default (Finance) Datasource
spring.datasource.url=jdbc:h2:file:${app.db.finance-path}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Auth Datasource
auth.datasource.url=jdbc:h2:file:${app.db.auth-path}
auth.datasource.driver-class-name=org.h2.Driver
auth.datasource.username=sa
auth.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Ensure social logic is completely removed
spring.flyway.enabled=false

jwt.secret=yourSuperSecretKeyThatIsAtLeast256BitsLongAndShouldBeStoredSecurely
